language: python
python:
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ibejohn818
  password:
    secure: Kd7ahP9NYQqZWA4VuregWAEoDAAevBVgt8PkKHRzAALDK704UnnwN+yIqp3cjdeMqMdhFMHowm3wru5JLUYoUbl5nTc6zYYxjvxnxn9pPfG/4foPVYB/ECEr9S9/zVxXqxgfe0GOLLKKbFUMK0tcTn7OS7bRyFP78xHMtnhbRp/+K1vZTWb/JLc2Gi7gCgxZNcSPbvbNcq/s0f+TfONz19k0AFOHxPpOdPAQ5geAuw1lyDj3gfLIuKHyYMiRBpNvAEloJOfqrXb3ULRLRp6xHZuy3vUeDJrGNeOaScP5Lst0ERq/vEuRya+3Re6pDOSbO1EQ/1v8xcpZIbXhHWxPEe6X4HuK8bWpXfH60pzGQIRCVHA31IFNNhWc4qUsTRyGf7ydmXCvYrhvXB091T2ak5GthlOQbqyRVfwZZD/+xnDH8XKP+rcnGgdPv5Kh+GtxjpMnmdG1ZOJxdRwdsAQTCp3b2pSpXGDI8VGOuQxWX1WDAsK2MtLx8jY/HCje1J0PPky3wjb6W6kdlinTlu/OerBBfjphubPmdVbxvrYzsswBLI4lNH7Yo1N3lPFQtGgWYcrvg9a3z2ssvRUaBz7m8lsjwvfQ2LGFR2XyVz8swrBSKCO2UVAqHRjAKaQBHlpZ8ry+tqd5fFE7XwAoCTaVp7DyG9ftWbPsnbdVLrA9XkQ=
  on:
    tags: true
    repo: ibejohn818/ec2ips
    python: 2.7
